import { TeamOutput } from '../src/entities';

export const teams: TeamOutput[] = [
  {
    id: 21,
    name: 'Alemanha',
    code: 'ALE',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/G/Germany-logo-9830108515-seeklogo.com.png',
  },
  {
    id: 20,
    name: 'Argentina',
    code: 'ARG',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/B/bandera-argentina-logo-3BB4D648D3-seeklogo.com.png',
  },
  {
    id: 33,
    name: 'Atlético-GO',
    code: 'ATG',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/A/atletico-clube-goianiense-logo-0F82BD40FC-seeklogo.com.png',
  },
  {
    id: 6,
    name: 'Atlético-MG',
    code: 'CAM',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/A/atletico-mg-logo-62B8B96E45-seeklogo.com.png',
  },
  {
    id: 8,
    name: 'Atlético-PR',
    code: 'CAP',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/A/atletico-pr-logo-CD2FBD1390-seeklogo.com.png',
  },
  {
    id: 7,
    name: 'Bahia',
    code: 'BAH',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/B/Bahia-logo-0BF5C9A502-seeklogo.com.png',
  },
  {
    id: 25,
    name: 'Borussia Dortmund',
    code: 'BOR',
    country: 'Alemanha',
    type: 'club',
    logo: 'https://seeklogo.com/images/B/borussia-dortmund-logo-CE073A17B3-seeklogo.com.png',
  },
  {
    id: 5,
    name: 'Botafogo',
    code: 'BOT',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/B/Botafogo_de_Futebol_e_Regatas-logo-4E0AF07AD3-seeklogo.com.png',
  },
  {
    id: 3,
    name: 'Bragantino',
    code: 'BRG',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/B/bragantino-2020-logo-3EC44F6C66-seeklogo.com.png',
  },
  {
    id: 35,
    name: 'Corinthians',
    code: 'COR',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/C/Corinthians_Bras_and__227_o-logo-E92E44B595-seeklogo.com.png',
  },
  {
    id: 11,
    name: 'Criciúma',
    code: 'CRI',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/C/criciuma-esporte-clube-logo-29371E1CC8-seeklogo.com.png',
  },
  {
    id: 38,
    name: 'Cruzeiro',
    code: 'CRU',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/C/Cruzeiro-logo-B4A6024EAF-seeklogo.com.png',
  },
  {
    id: 39,
    name: 'Cuiabá',
    code: 'CUI',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/C/cuiaba-esporte-clube-logo-C39FD2778A-seeklogo.com.png',
  },
  {
    id: 28,
    name: 'Escócia',
    code: 'ESC',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/B/bandeira-da-escocia-logo-EB9C96D19E-seeklogo.com.png',
  },
  {
    id: 27,
    name: 'Espanha',
    code: 'ESP',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/B/bandeira-espanha-logo-76731839FE-seeklogo.com.png',
  },
  {
    id: 4,
    name: 'Flamengo',
    code: 'FLA',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/C/Clube_de_Regatas_do_Flamengo-logo-35138A63C6-seeklogo.com.png',
  },
  {
    id: 32,
    name: 'Fluminense',
    code: 'FLU',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/F/Fluminense_Football_Club-logo-D1527EDB90-seeklogo.com.png',
  },
  {
    id: 12,
    name: 'Fortaleza',
    code: 'FOR',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/F/Fortaleza_Esporte_Clube_de_Fortaleza-CE-logo-3AE1E4EAF6-seeklogo.com.png',
  },
  {
    id: 9,
    name: 'Grêmio',
    code: 'GRE',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/G/Gremio-logo-63728B406B-seeklogo.com.png',
  },
  {
    id: 29,
    name: 'Hungria',
    code: 'HUN',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/H/hungary-flag-logo-8B61EF20F8-seeklogo.com.png',
  },
  {
    id: 10,
    name: 'Internacional',
    code: 'INT',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/S/sc-internacional-rs-y100-logo-9C78954B54-seeklogo.com.png',
  },
  {
    id: 31,
    name: 'Juventude',
    code: 'JUV',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/E/EC_Juventude-logo-878B96020B-seeklogo.com.png',
  },
  {
    id: 26,
    name: 'Palmeiras',
    code: 'PAL',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/P/palmeiras-logo-9ECCEA469E-seeklogo.com.png',
  },
  {
    id: 19,
    name: 'Real Madrid',
    code: 'RMA',
    country: 'Espanha',
    type: 'club',
    logo: 'https://seeklogo.com/images/R/Real_Madrid_Club_de_Futbol-logo-60682932F8-seeklogo.com.png',
  },
  {
    id: 36,
    name: 'São Paulo',
    code: 'SAO',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/S/Sao_Paulo_Futebol_Clube-logo-F291AB0A19-seeklogo.com.png',
  },
  {
    id: 30,
    name: 'Suíça',
    code: 'SUI',
    country: null,
    type: 'selection',
    logo: 'https://seeklogo.com/images/S/Switzerland-logo-A9E90D8252-seeklogo.com.png',
  },
  {
    id: 37,
    name: 'Vasco',
    code: 'VAS',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/V/Vasco_Da_Gama-logo-99E0C20F34-seeklogo.com.png',
  },
  {
    id: 34,
    name: 'Vitória',
    code: 'VIT',
    country: 'Brasil',
    type: 'club',
    logo: 'https://seeklogo.com/images/E/Esporte_Clube_Vitoria_de_Salvador-BA-logo-9ACB56091F-seeklogo.com.png',
  },
];
